//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbfirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_M_Item()
        {
            this.TB_T_TransactionDetail = new HashSet<TB_T_TransactionDetail>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public int price { get; set; }
        public int stock { get; set; }
        public int TB_M_Suppliers_id { get; set; }
        public bool isDelete { get; set; }
    
        public virtual TB_M_Supplier TB_M_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_TransactionDetail> TB_T_TransactionDetail { get; set; }
    }
}
